<a href="https://colab.research.google.com/github/imshiv-10/Deep-Learning/blob/main/PyTorch_work_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 KB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [3]:
import torch

## Tensors & Gradients

In [4]:
ls

sample_data/


In [5]:
t1 = torch.tensor(4., dtype=torch.float32)

In [6]:
t1

tensor(4.)

In [7]:
t1.dtype

torch.float32

In [8]:
# vector
t2 = torch.tensor([1.,2,3,4,5])

In [9]:
t2

tensor([1., 2., 3., 4., 5.])

In [10]:
t2.dtype

torch.float32

In [11]:
type(t2)

torch.Tensor

In [12]:
# Matrix # 1 Dimensional matrix
t3 = torch.tensor([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])

In [13]:
t3.size()

torch.Size([4, 2])

In [14]:
# Matrix 3-dimensional matrix
t4 = torch.tensor([[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],
                   [[13,14,15,16],
                   [17,18,19,20],
                   [21,22,23,24]]])

In [15]:
t4

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [16]:
t4.size()

torch.Size([2, 3, 4])

In [17]:
t4.shape

torch.Size([2, 3, 4])

# Tensor operations and gradients

We combine the tensors with the usual arithmetic operations. Let's look an example

In [18]:
# creating the tensors 
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
_bias = torch.tensor(5., requires_grad=True)

In [19]:
x, w

(tensor(3.), tensor(4., requires_grad=True))

we have created the 3 tensors if x tensor will not included for derivative's

lets function f(x)== y  = wx + _bias

In [20]:
# linear function
y = w * x + _bias

In [21]:
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

In [22]:
y.backward()

In [23]:
y

tensor(17., grad_fn=<AddBackward0>)

The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [24]:
type(x.grad)

NoneType

In [25]:
x

tensor(3.)

In [26]:
type(w.grad), w.grad

(torch.Tensor, tensor(3.))

In [27]:
_bias.grad

tensor(1.)

In [28]:
print('df/dx:', x.grad)
print('df/dw:',w.grad)
print('df/d_bias', _bias.grad)

df/dx: None
df/dw: tensor(3.)
df/d_bias tensor(1.)


In [29]:
import numpy as np


In [30]:
x = np.array([[1,2], [3,4]])

In [31]:
x.shape, x

((2, 2), array([[1, 2],
        [3, 4]]))

In [32]:
matrix_t = torch.from_numpy(x)

In [33]:
matrix_t , type(matrix_t)

(tensor([[1, 2],
         [3, 4]]), torch.Tensor)

Let's verify that the numpy array and torch tensor have similar data types.

In [34]:
x.dtype, matrix_t.dtype

(dtype('int64'), torch.int64)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

In [35]:
import jovian
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


In [36]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [37]:
 torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
 torch.zeros([5, 5], dtype=torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [39]:
cuda0 = torch.device('cuda:0')

In [40]:
cuda0

device(type='cuda', index=0)

In [41]:
device = torch.device("cuda:0")

In [42]:
k = torch.ones([2, 4], dtype=torch.float64, device=cuda0)

In [43]:
k

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [44]:
type(k[0][0].item())

float

In [45]:
x = torch.tensor([[1.,-1], [1,1]], requires_grad=True)

In [46]:
out =  x.pow(2).sum()

In [47]:
out.backward()

In [48]:
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [49]:
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [50]:
x.T

tensor([[ 1.,  1.],
        [-1.,  1.]], grad_fn=<PermuteBackward0>)

In [51]:
x.H

tensor([[ 1.,  1.],
        [-1.,  1.]], grad_fn=<TransposeBackward0>)

In [52]:
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [56]:
y = x.new_tensor

In [58]:
y = torch.tensor([1,2])

In [59]:
y

tensor([1, 2])

In [60]:
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [65]:
x.new_full((10,10),3.14)

tensor([[3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400],
        [3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400, 3.1400,
         3.1400]])

In [66]:
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [68]:
?x.new_empty

In [69]:
tensor = torch.ones(())

In [73]:
tensor.item()

1.0

In [75]:
tensor.new_empty((10,10,10))

tensor([[[ 1.4013e-45,  0.0000e+00,  1.1228e+03,  0.0000e+00,  3.3631e-44,
                  nan,  5.3989e-07,  4.5799e-41,  1.4013e-45,  4.5799e-41],
         [ 0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,  1.4013e-45,
           8.4078e-45,  2.9427e-44,  0.0000e+00,  1.1227e+03,  0.0000e+00],
         [ 3.5732e-12,  4.5799e-41,  1.4013e-45,         nan,  1.4013e-45,
           0.0000e+00,  1.4013e-45,  2.2421e-44,  1.4013e-45,  0.0000e+00],
         [ 1.1228e+03,  0.0000e+00,  4.2039e-45,  0.0000e+00,  1.1227e+03,
           0.0000e+00,  1.1228e+03,  0.0000e+00,  1.1228e+03,  0.0000e+00],
         [ 2.8026e-44,  0.0000e+00,  1.3723e-38,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  1.3723e-38,  0.0000e+00,  1.4013e-45,  2.5223e-44],
         [ 1.4013e-45,  2.8026e-44,  2.8026e-44,  2.5223e-44,  1.3723e-38,
           0.0000e+00,  0.0000e+00,  0.0000e+00,  1.3723e-38,  0.0000e+00],
         [ 1.4013e-45,  2.9427e-44,  1.4013e-45,  3.2230e-44,  2.8026e-44,
           2.9427e-

In [78]:
?x.is_cuda

In [79]:
x.is_cuda

False

In [80]:
k

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [81]:
k.is_cuda

True

In [83]:
?x.is_quantized

In [84]:
import torch

# Create a tensor on the CPU
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print(x.device) # prints: device('cpu')

# Transfer the tensor to a GPU
if torch.cuda.is_available():
    x = x.to('cuda')
    print(x.device) # prints: device('cuda:0')


cpu
cuda:0


In [86]:
x.to('cuda')

tensor([1., 2., 3.], device='cuda:0')

In [88]:
x.new_empty

<function Tensor.new_empty>

In [89]:
x

tensor([1., 2., 3.], device='cuda:0')

In [91]:
x.ndim

1

In [93]:
k.ndim

2

In [94]:
c = torch.randn(4,dtype=torch.cfloat)

In [95]:
c

tensor([-1.2550+1.0104j, -0.2099-0.6871j,  1.0479-0.7040j,  0.3967-0.5999j])

In [96]:
c.real

tensor([-1.2550, -0.2099,  1.0479,  0.3967])

In [98]:
c.imag

tensor([ 1.0104, -0.6871, -0.7040, -0.5999])

In [99]:
c

tensor([-1.2550+1.0104j, -0.2099-0.6871j,  1.0479-0.7040j,  0.3967-0.5999j])

In [100]:
c.to("cuda")

tensor([-1.2550+1.0104j, -0.2099-0.6871j,  1.0479-0.7040j,  0.3967-0.5999j],
       device='cuda:0')

In [101]:
c.real

tensor([-1.2550, -0.2099,  1.0479,  0.3967])

In [102]:
c.imag

tensor([ 1.0104, -0.6871, -0.7040, -0.5999])

In [103]:
c.abs()

tensor([1.6112, 0.7185, 1.2624, 0.7192])

In [106]:
c.abs_

<function Tensor.abs_>

In [107]:
c.absolute

<function Tensor.absolute>

In [108]:
c.acos

<function Tensor.acos>