<a href="https://colab.research.google.com/github/imshiv-10/Deep-Learning/blob/main/PyTorch_work_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 KB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [2]:
import torch

## Tensors & Gradients

In [3]:
ls

sample_data/


In [16]:
t1 = torch.tensor(4., dtype=torch.float32)

In [17]:
t1

tensor(4.)

In [18]:
t1.dtype

torch.float32

In [19]:
# vector
t2 = torch.tensor([1.,2,3,4,5])

In [20]:
t2

tensor([1., 2., 3., 4., 5.])

In [21]:
t2.dtype

torch.float32

In [22]:
type(t2)

torch.Tensor

In [24]:
# Matrix # 1 Dimensional matrix
t3 = torch.tensor([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])

In [27]:
t3.size()

torch.Size([4, 2])

In [30]:
# Matrix 3-dimensional matrix
t4 = torch.tensor([[[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]],
                   [[13,14,15,16],
                   [17,18,19,20],
                   [21,22,23,24]]])

In [31]:
t4

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [32]:
t4.size()

torch.Size([2, 3, 4])

In [34]:
t4.shape

torch.Size([2, 3, 4])

# Tensor operations and gradients

We combine the tensors with the usual arithmetic operations. Let's look an example

In [39]:
# creating the tensors 
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
_bias = torch.tensor(5., requires_grad=True)

In [38]:
x, y, w

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

# we have created the 3 tensors if x tensor will not included for derivative's

lets function f(x)== y  = wx + _bias

In [40]:
# linear function
y = w * x + _bias

In [41]:
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

In [42]:
y.backward()

In [43]:
y

tensor(17., grad_fn=<AddBackward0>)

The derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [48]:
type(x.grad)

NoneType

In [46]:
x

tensor(3.)

In [50]:
type(w.grad), w.grad

(torch.Tensor, tensor(3.))

In [52]:
_bias.grad

tensor(1.)

In [53]:
print('df/dx:', x.grad)
print('df/dw:',w.grad)
print('df/d_bias', _bias.grad)

df/dx: None
df/dw: tensor(3.)
df/d_bias tensor(1.)


In [54]:
import numpy as np


In [55]:
x = np.array([[1,2], [3,4]])

In [58]:
x.shape, x

((2, 2), array([[1, 2],
        [3, 4]]))

In [59]:
matrix_t = torch.from_numpy(x)

In [61]:
matrix_t , type(matrix_t)

(tensor([[1, 2],
         [3, 4]]), torch.Tensor)

In [62]:
x.dtype, matrix_t.dtype

(dtype('int64'), torch.int64)